# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0e712cb338327aeab6993eac718963662cc5ec7613c4d8953af576f488f1a57be3787d7faf5000feee008699d556c7eee8fa11752ea437d38fcfaf63511a1a3

test:
  secret_key_base: 6181d91e16102ff7e8991a262c5aadcc569769eb9b1c3142797c166625d0a046b17a813f0172d8317db37e5b7b6ce9af33f9bbfb44eb3eb1817db4e5d2808f42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
